### ISSUE TITLE
RecognitionEngine Speaktoit is not working

### ISSUE THREAD

**Issue by Ranjith1992** [api-ai/apiai-android-client#49]
**Application is working fine when RecognitionEngine is set to system (AIConfiguration.RecognitionEngine.System).
I changed RecognitionEngine "System " to "Speaktoit"(AIConfiguration.RecognitionEngine.Speaktoit) Application is not working.
Following Exception is occurring.**

07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err: java.io.IOException: Stream closed
07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err:     at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:151)
07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err:     at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err:     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
07-06 18:01:39.339 21358-22502/ai.api.sample W/System.err:     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at java.io.InputStreamReader.read(InputStreamReader.java:184)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at java.io.Reader.read(Reader.java:140)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.util.IOUtils.copy(IOUtils.java:140)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.util.IOUtils.copy(IOUtils.java:131)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.util.IOUtils.readAll(IOUtils.java:126)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.util.IOUtils.readAll(IOUtils.java:102)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.util.IOUtils.readAll(IOUtils.java:114)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.http.HttpClient.getErrorString(HttpClient.java:158)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.AIDataService.doSoundRequest(AIDataService.java:799)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.AIDataService.doSoundRequest(AIDataService.java:743)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.AIDataService.voiceRequest(AIDataService.java:288)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.AIDataService.voiceRequest(AIDataService.java:253)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.services.SpeaktoitRecognitionServiceImpl$RecognizeTask.doInBackground(SpeaktoitRecognitionServiceImpl.java:380)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at ai.api.services.SpeaktoitRecognitionServiceImpl$RecognizeTask.doInBackground(SpeaktoitRecognitionServiceImpl.java:362)
07-06 18:01:39.340 21358-22502/ai.api.sample W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-06 18:01:39.341 21358-22502/ai.api.sample W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 18:01:39.341 21358-22502/ai.api.sample W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-06 18:01:39.341 21358-22502/ai.api.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-06 18:01:39.341 21358-22502/ai.api.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-06 18:01:39.341 21358-22502/ai.api.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out: 2017-07-06 18:01:39,341 ERROR An exception occurred processing Appender Console java.lang.NullPointerException: Attempt to get length of null array
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.util.ReflectionUtil.getCurrentStackTrace(ReflectionUtil.java:274)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:116)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.impl.Log4jLogEvent.getThrownProxy(Log4jLogEvent.java:323)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:64)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:36)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:196)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:55)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:71)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:108)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
07-06 18:01:39.346 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:409)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:112)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:727)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:716)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:354)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.AIDataService.doSoundRequest(AIDataService.java:813)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.AIDataService.doSoundRequest(AIDataService.java:743)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.AIDataService.voiceRequest(AIDataService.java:288)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.AIDataService.voiceRequest(AIDataService.java:253)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.services.SpeaktoitRecognitionServiceImpl$RecognizeTask.doInBackground(SpeaktoitRecognitionServiceImpl.java:380)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at ai.api.services.SpeaktoitRecognitionServiceImpl$RecognizeTask.doInBackground(SpeaktoitRecognitionServiceImpl.java:362)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-06 18:01:39.347 21358-22502/ai.api.sample I/System.out:     at java.lang.Thread.run(Thread.java:761)
07-06 18:01:39.349 21358-22502/ai.api.sample E/TEST:  doInBackground e*****ai.api.AIServiceException: Can't make request to the API.AI service. Please, check connection settings and API.AI keys.
07-06 18:01:39.391 21358-21358/ai.api.sample D/ai.api.sample.AIButtonSampleActivity: onCancelled
07-06 18:01:39.391 21358-21358/ai.api.sample D/ai.api.sample.AIButtonSampleActivity: onError*

Kindly help me to solve this issue.

**Comment by folomeev** [comment]
Speaktoit recognition was marked as deprecated some time ago and already not supported.

**Comment by Ranjith1992** [comment]
I want to pass audio input.What i  will do ?

**Comment by folomeev** [comment]
Just leave the default RecognitionEngine value ("System").
If you want to decode standalone audio file I may recommend you to take a look at [Voice client sample code](https://github.com/api-ai/apiai-java-client/tree/master/samples/clients/voice-client)

**Comment by Ranjith1992** [comment]
I need the input audio file .Because if the command is not an api.ai command(ex : what is the weather ?),
I have to  to pass this to my google assistant app(created using grpc).
