### ISSUE TITLE
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'. 

### ISSUE THREAD

**Issue by CCCCoder** [api-ai/apiai-android-client#56]
build.gradle:
apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    testCompile 'junit:junit:4.12'
    compile 'ai.api:libai:1.4.8'
    compile 'ai.api:sdk:2.0.7@aar'
// api.ai SDK dependencies
    compile 'com.google.code.gson:gson:2.3'
    compile 'commons-io:commons-io:2.4'
}

when i try to run the project:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.2\d7ef6ad7ff0711dd12fe409d62d72d6ed14516e0\log4j-api-2.2.jar
	File2: C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.2\c707664e020218f8529b9a5e55016ee15f0f82ac\log4j-core-2.2.jar

How to resolve？

**Comment by folomeev** [comment]
Remove following line from `build.gradle`:
```
compile 'ai.api:libai:1.4.8'
```

**Comment by CCCCoder** [comment]
@folomeev Thank for you reply, but remove this will cause class like 'AIResquest' not found : )

**Comment by folomeev** [comment]
No problem, put this one instead:
```
compile 'ai.api:libai:1.6.12'
```

**Comment by CCCCoder** [comment]
@folomeev Thanks!!!!!
