### ISSUE TITLE
display text with speech recognisation

### ISSUE THREAD

**Issue by vipulasri** [api-ai/apiai-android-client#58]
When a user is saying something, simultaneously display recognized text just like Google Assistant.
**Basically getting recognization results from AIService**

**Comment by vipulasri** [comment]
Got it: 

Just by setting a `PartialResultsListener` to AIService

```

if (aiService instanceof GoogleRecognitionServiceImpl) {
            ((GoogleRecognitionServiceImpl) aiService).setPartialResultsListener(new PartialResultsListener() {
                @Override
                public void onPartialResults(final List<String> partialResults) {
                    if (partialResultsListener != null) {
                        partialResultsListener.onPartialResults(partialResults);
                    }
                }
            });
        }
```

**Comment by kevinjmz** [comment]
hey @vipulasri , 
can you specify what are the contents of partialResultsListener object please? I would greatly appreciate your help. 

:)

**Comment by son2017** [comment]
hi @kevinjmz 
i tryed with your code but its working fine but while runnig its take same voice message in multiple time do you have any idea?
